apiVersion: v1
kind: Service
metadata:
  name: {{ template "phpmyfaq.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "phpmyfaq.name" . }}
    release: "{{ .Release.Name }}"

